<a href="https://colab.research.google.com/github/aliffianilhamf/PreprocessingData/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [156]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [157]:
data_set = pd.read_csv("preprocessing.csv")
x = data_set.iloc[:, 2:-1].values
y = data_set.iloc[:,-1].values

In [158]:
print(x)

[['KLOTOK SERIES' 11000 11000.0]
 ['BOTOL' 5000 10000.0]
 ['MAKANAN' 14000 nan]
 ['MINUMAN' 18000 18000.0]
 ['KLOTOK SERIES' 8000 8000.0]
 ['MAKANAN' 14000 14000.0]
 ['TROPICAL SERIES' 15000 nan]
 ['MAKANAN' 15000 15000.0]
 ['MAKANAN' 14000 14000.0]
 ['TROPICAL SERIES' 15000 15000.0]
 ['KLOTOK SERIES' 11000 22000.0]
 ['BOTOL' 5000 5000.0]
 ['ROKOK' 23000 23000.0]
 ['KLOTOK SERIES' 11000 11000.0]
 ['TROPICAL SERIES' 12000 12000.0]
 ['SNACK' 2000 2000.0]
 ['BOTOL' 5000 5000.0]
 ['KLOTOK SERIES' 11000 11000.0]
 ['KLOTOK SERIES' 11000 11000.0]
 ['KLOTOK SERIES' 8000 8000.0]
 ['KLOTOK SERIES' 8000 nan]
 ['KLOTOK SERIES' 11000 11000.0]
 ['MAKANAN' 14000 14000.0]
 ['MINUMAN' 5000 5000.0]
 ['KLOTOK SERIES' 8000 8000.0]
 ['MAKANAN' 14000 28000.0]
 ['MINUMAN' 5000 10000.0]
 ['SNACK' 2000 2000.0]
 ['KLOTOK SERIES' 11000 22000.0]
 ['KLOTOK SERIES' 8000 8000.0]
 ['KLOTOK SERIES' 11000 11000.0]
 ['SNACK' 15000 15000.0]
 ['KLOTOK SERIES' 11000 11000.0]
 ['TROPICAL SERIES' 15000 15000.0]
 ['SNACK' 200

In [159]:
print(y)

['CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'RETURN' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'RETURN' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'RETURN' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'RETURN' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH'
 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH' 'CASH

In [160]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [161]:
print(x)

[['KLOTOK SERIES' 11000.0 11000.0]
 ['BOTOL' 5000.0 10000.0]
 ['MAKANAN' 14000.0 13034.574468085106]
 ['MINUMAN' 18000.0 18000.0]
 ['KLOTOK SERIES' 8000.0 8000.0]
 ['MAKANAN' 14000.0 14000.0]
 ['TROPICAL SERIES' 15000.0 13034.574468085106]
 ['MAKANAN' 15000.0 15000.0]
 ['MAKANAN' 14000.0 14000.0]
 ['TROPICAL SERIES' 15000.0 15000.0]
 ['KLOTOK SERIES' 11000.0 22000.0]
 ['BOTOL' 5000.0 5000.0]
 ['ROKOK' 23000.0 23000.0]
 ['KLOTOK SERIES' 11000.0 11000.0]
 ['TROPICAL SERIES' 12000.0 12000.0]
 ['SNACK' 2000.0 2000.0]
 ['BOTOL' 5000.0 5000.0]
 ['KLOTOK SERIES' 11000.0 11000.0]
 ['KLOTOK SERIES' 11000.0 11000.0]
 ['KLOTOK SERIES' 8000.0 8000.0]
 ['KLOTOK SERIES' 8000.0 13034.574468085106]
 ['KLOTOK SERIES' 11000.0 11000.0]
 ['MAKANAN' 14000.0 14000.0]
 ['MINUMAN' 5000.0 5000.0]
 ['KLOTOK SERIES' 8000.0 8000.0]
 ['MAKANAN' 14000.0 28000.0]
 ['MINUMAN' 5000.0 10000.0]
 ['SNACK' 2000.0 2000.0]
 ['KLOTOK SERIES' 11000.0 22000.0]
 ['KLOTOK SERIES' 8000.0 8000.0]
 ['KLOTOK SERIES' 11000.0 11000.0]

In [162]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Encoding data kategori (Atribut)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [163]:
print(x)

[[0.0 1.0 0.0 ... 0.0 11000.0 11000.0]
 [1.0 0.0 0.0 ... 0.0 5000.0 10000.0]
 [0.0 0.0 1.0 ... 0.0 14000.0 13034.574468085106]
 ...
 [0.0 1.0 0.0 ... 0.0 11000.0 11000.0]
 [0.0 0.0 0.0 ... 1.0 15000.0 15000.0]
 [0.0 0.0 1.0 ... 0.0 14000.0 14000.0]]


In [164]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [165]:
print(y)

[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [166]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [167]:
print(x_train)

[[0.0 0.0 0.0 ... 0.0 12000.0 12000.0]
 [0.0 0.0 0.0 ... 0.0 11000.0 11000.0]
 [0.0 1.0 0.0 ... 0.0 11000.0 11000.0]
 ...
 [0.0 0.0 0.0 ... 0.0 16000.0 16000.0]
 [0.0 1.0 0.0 ... 0.0 11000.0 11000.0]
 [0.0 1.0 0.0 ... 0.0 8000.0 13034.574468085106]]


In [168]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 5000.0 10000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 8000.0 8000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 2000.0 4000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 11000.0 44000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 12000.0 24000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 12000.0 12000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 11000.0 44000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 8000.0 8000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 8000.0 8000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5000.0 5000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 5000.0 10000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 11000.0 11000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5000.0 5000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 11000.0 11000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 16000.0 16000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 2000.0 2000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 5000.0 5000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 5000.0 5000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 12000.0 12000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 15000.0 15000.0]


In [169]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [170]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]


In [171]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 8:] = sc.fit_transform(x_train[:, 8:])
x_test[:, 8:] = sc.transform(x_test[:, 8:])

In [172]:
print(x_train)

[[0.0 0.0 0.0 ... 0.0 0.20316397694534472 -0.16570545089361868]
 [0.0 0.0 0.0 ... 0.0 -0.03700756457368731 -0.3208295415300554]
 [0.0 1.0 0.0 ... 0.0 -0.03700756457368731 -0.3208295415300554]
 ...
 [0.0 0.0 0.0 ... 0.0 1.1638501430214727 0.45479091165212815]
 [0.0 1.0 0.0 ... 0.0 -0.03700756457368731 -0.3208295415300554]
 [0.0 1.0 0.0 ... 0.0 -0.7575221891307834 -0.00521802733624144]]


In [173]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 -1.4780368136878794
  -0.47595363216649206]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.7575221891307834 -0.7862018134393655]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 -2.1985514382449756 -1.4066981759851123]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.03700756457368731 4.798265449472356]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.20316397694534472 1.6957836367436216]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.20316397694534472
  -0.16570545089361868]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.03700756457368731 4.798265449472356]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.7575221891307834 -0.7862018134393655]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.7575221891307834 -0.7862018134393655]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.4780368136878794 -1.2515740853486756]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 -1.4780368136878794
  -0.47595363216649206]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.03700756457368731
  -0.3208295415300554]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.4780368136878794 -1.2515740853486756]
 [0.0 1.0 0.0 0.